enum ReservationTypes {
  MAKE_RESERVATION = 'MAKE_RESERVATION',
  SUCCESS_RESERVATION = 'SUCCESS_RESERVATION',
  FAILED_RESERVATION = 'FAILED_RESERVATION',
  ERROR_RESERVATION = 'ERROR_RESERVATION',
}

export default ReservationTypes;
