enum RoomsActionTypes {
  REQUEST_ROOMS = 'REQUEST_ROOMS',
  FETCH_ROOMS = 'FETCH_ROOMS',

  SHOW_LOADING_INIT = 'INIT/SHOW_LOADING',
  HIDE_LOADING_INIT = 'INIT/HIDE_LOADING',

  SHOW_LOADING_ADDITIONAL = 'ADDITION/SHOW_LOADING',
  HIDE_LOADING_ADDITIONAL = 'ADDITION/HIDE_LOADING',
}

export default RoomsActionTypes;
