enum RoomsActionTypes {
  REQUEST_ROOMS = 'REQUEST_ROOMS',
  FETCH_ROOMS = 'FETCH_ROOMS',

  SHOW_LOADING_INIT = 'INIT/SHOW_LOADING',
  HIDE_LOADING_INIT = 'INIT/HIDE_LOADING',

  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
}

export default RoomsActionTypes;
