enum SignUpActionsTypes {
  SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST',
  SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR',
}

export default SignUpActionsTypes;
