enum AuthActionsTypes {
  SET_AUTH_USER_DATA = 'SET_AUTH_USER_DATA',
  GET_USER_STATUS = 'GET_USER_STATUS',
  USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST',
  SET_AUTH_USER_FAILED_STATUS = 'SET_AUTH_USER_FAILED_STATUS',
}

export default AuthActionsTypes;
