enum AuthActionsTypes {
  SET_AUTH_USER_DATA = 'SET_AUTH_USER_DATA',
  USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST',
  USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS',
  SET_USER_LOGOUT_STATUS = 'SET_USER_LOGOUT_STATUS',
  SET_AUTH_USER_FAILED_STATUS = 'SET_AUTH_USER_FAILED_STATUS',
}

export default AuthActionsTypes;
