enum PasswordRecoveryActionsTypes {
  PASSWORD_RECOVERY_REQUEST = 'PASSWORD_RECOVERY_REQUEST',
  PASSWORD_RECOVERY_SUCCESS = 'PASSWORD_RECOVERY_SUCCESS',
  PASSWORD_RECOVERY_FAILED = 'PASSWORD_RECOVERY_FAILED',
}

export default PasswordRecoveryActionsTypes;
