enum TestCounterActionTypes {
  COUNTER_INCREMENT = 'COUNTER_INCREMENT',
  COUNTER_DECREMENT = 'COUNTER_DECREMENT',
  ASYNC_COUNTER_INCREMENT = 'ASYNC_COUNTER_INCREMENT',
  ASYNC_COUNTER_DECREMENT = 'ASYNC_COUNTER_DECREMENT',
}

export default TestCounterActionTypes;
